name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".github/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".github/**"

env:
  DOCKER_REGISTRY: docker.ilhwan.net:5000

jobs:

  Docker_Build_And_Push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/minigame-web:latest